packages:
  - 'packages/*'
  - 'apps/*'
allowBuilds:
  electron: true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
  tree-sitter-bash: true
  tree-sitter-powershell: true
confirmModulesPurge: false
nodeLinker: hoisted
